HOST: https://nmoneys.apphb.com/api/v1

--- nMoneys API v1 ---
---
Welcome to NMoneys' API documentation. Here you will find what you can do with this API
---

Provides information about resources available through the API.
OPTIONS /
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"_links": [
		{
			"rel": "_self",
			"href": "/api/v1",
			"method": "OPTIONS"
		},
		{
			"rel": "currencies",
			"href": "/api/v1/currencies",
			"method": "GET"
		}
	]
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request

--
Currency Resources
Resources related to ISO 4217 currencies.
--

Provides information about supported currencies. Obsolete currencies are returned.
OPTIONS /currencies
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"_links": [
		{
			"rel": "_self",
			"href": "/v1/api/currencies",
			"method": "OPTIONS"
		},
		{
			"rel": "self",
			"href": "/v1/api/currencies",
			"method": "GET"
		},
		{
			"rel": "currency",
			"href": "/v1/api/currencies/AED",
			"method": "GET"
		},
		...
		{
			"rel": "currency",
			"href": "/v1/api/currencies/ZWL",
			"method": "GET"
		}
	]
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request

List supported currencies. Obsolete currencies are returned.
GET /currencies
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"snapshots": [
		...,
		{
			"isoCode": "EUR",
			"numericCode": 978,
			"englishName": "Euro"
		},
		...,
		{
			"isoCode": "ZMK",
			"numericCode": 894,
			"englishName": "Zambian Kwacha",
			"isObsolete" : true
		},
		...,
	]
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request

Provides information about a currency.
OPTIONS /currencies/{isoCode}
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"_links": [
		{
			"rel": "_self",
			"href": "/v1/api/currency/EUR",
			"method": "OPTIONS"
		},
		{
			"rel": "self",
			"href": "/v1/api/currency/EUR",
			"method": "GET"
		},
		{
			"rel": "parent",
			"href": "/v1/api/currencies",
			"method": "GET"
		},
		{
			"rel": "format",
			"href": "/v1/api/currencies/EUR/format/0",
			"method": "GET"
		}
	]
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request
+++++
< 404

Get detailed information about a currency.
GET /currencies/{isoCode}
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"detail": {
		"isoCode": "EUR",
		"numericCode": 978,
		"englishName": "Euro",
		"nativeName": "Euro",
		"symbol": "€",
		"isObsolete": false
	}
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request
+++++
< 404

--
Money Resources
Resources related to monetary quantities.
--

Provides information about formatting a monetary amount according to its currency.
OPTIONS /currencies/{isoCode}/format/{amount}
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"_links": [
		{
			"rel": "_self",
			"href":"/api/v1/currencies/EUR/format/123",
			"method": "OPTIONS"
		},
		{
			"rel": "self",
			"href":"/api/v1/currencies/EUR/format/123",
			"method": "GET"
		},
		{
			"rel": "parent",
			"href":"/api/v1/currencies/EUR",
			"method": "GET"
		}
	]
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request
+++++
< 404

Allows formatting a monetary amount according to its currency.
GET /currencies/{isoCode}/format/{amount}
> Accept: application/json
> Api_Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"money": {
		"amount": 123,
		"isoCode": "EUR",
		"representation": "123,00 €",
		"amountRepresentation": "123,00"
	}
}
+++++
< 401
+++++
< 429
Retry-After: number of seconds to wait before making a new request
+++++
< 404