HOST: https://nmoneys.apphb.com/api/v1

--- nMoneys API v1 ---
---
Welcome to NMoneys' API documentation. Here you will find what you can do with this API
---

--
Currency Resources
The following is a section of resources related to ISO 4217 currencies
--
List current supported currencies.
GET /currencies
> Accept: application/json
> Api-Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"snapshots": [
		{
			"isoCode": "USD",
			"numericCode":978,
			"englishName": "Euro"
		}
	]
}


Get detailed information about a currency.
GET /currencies/{isoCode}
> Accept: application/json
> Api-Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"detail": {
		"isoCode":"EUR"
		"numericCode":978,
		"englishName":"Euro",
		"nativeName":"Euro",
		"symbol":"€",
		"isObsolete":false
	}
}

Allows formatting a monetary amount according to its currency.
GET /currencies/{isoCode}/format/{amount}
> Accept: application/json
> Api-Key: your API key
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"money": {
		"amount":123,
		"isoCode":"EUR"
		"representation":"123,00 €",
		"amountRepresentation":"123,00"
	}
}

Allows formatting a monetary amount according to its currency.
POST /currencies/{isoCode}/format
> Accept: application/json
> Api-Key: your API key
{ "amount": "123.6" }
< 200
< Content-Type: application/json
< X-Rate-Limit-Limit: number of requests allowed in period
< X-Rate-Limit-Remaining: number of requests allowed in period
< X-Rate-Limit-Reset: number of seconds left in period
{
	"money": {
		"amount":123.6,
		"isoCode":"EUR",
		"representation":"123,60 €",
		"amountRepresentation":"123,60"
	}
}